Repository dds-project-f19/dds-frontend, pull requests merged in 2019-12, with the labels that each got.

#15 Workspace
  package-lock.json
  package.json
  src/features/WorkerItem/WorkerItem.tsx
  src/features/WorkerItem/index.ts
  src/features/Workspace/ItemList/ItemList.tsx
  src/features/Workspace/ItemList/index.ts
  src/features/Workspace/Workspace.tsx
  src/features/Workspace/WorkspaceContainer.tsx
  src/features/Workspace/WorkspaceWindow/WorkspaceWindow.tsx
  src/features/Workspace/WorkspaceWindow/index.ts
  src/features/Workspace/index.ts
  src/modules/App/App.tsx
  src/modules/WorkspacePage/WorkspacePage.tsx
  src/services/api/Api.ts
  src/shared/types/models.ts
  src/shared/workspaces/Workspaces.tsx
  src/shared/workspaces/index.ts
Labels: enhancement

#14 Manager page
  package-lock.json
  package.json
  src/features/LoginForm/LoginForm.tsx
  src/features/LoginForm/LoginFormContainer.tsx
  src/features/RegistrationForm/index.ts
  src/features/WorkerRegistrationForm/WorkerRegistrationForm.tsx
  src/features/WorkerRegistrationForm/WorkerRegistrationFormContainer.tsx
  src/features/WorkerRegistrationForm/index.ts
  src/features/WorkerScheduleForm/WorkerScheduleForm.tsx
  src/features/WorkerScheduleForm/WorkerScheduleFormContainer.tsx
  src/features/WorkerScheduleForm/index.ts
  src/modules/App/App.tsx
  src/modules/App/AppContainer.test.tsx
  src/modules/App/AppContainer.tsx
  src/modules/App/index.ts
  src/modules/AuthorizationPage/AuthorizationPage.tsx
  src/modules/ManagerPage/ManagerPage.tsx
  src/modules/ManagerPage/index.ts
  src/services/api/Api.ts
  src/shared/constants.ts
  src/shared/types/models.ts
Labels: enhancement

#21 Admin page
  src/features/ManagerRegistrationForm/ManagerRegistrationForm.tsx
  src/features/ManagerRegistrationForm/ManagerRegistrationFormContainer.tsx
  src/features/ManagerRegistrationForm/index.ts
  src/modules/AdminPage/AdminPage.tsx
  src/modules/AdminPage/index.ts
  src/modules/App/App.tsx
  src/modules/App/AppContainer.tsx
  src/shared/constants.ts
Labels: enhancement

#24 Create Node.js build action
  .github/workflows/nodejs.yml
Labels: enhancement

#27 Moved the item count form to its tab
  src/features/WorkerRegistrationForm/WorkerRegistrationForm.tsx
  src/features/WorkerScheduleForm/WorkerScheduleForm.tsx
  src/features/WorkerScheduleForm/WorkerScheduleFormContainer.tsx
  src/features/WorkspaceItemsForm/WorkspaceItemsForm.tsx
  src/features/WorkspaceItemsForm/WorkspaceItemsFormContainer.tsx
  src/features/WorkspaceItemsForm/index.ts
  src/modules/ManagerPage/ManagerPage.tsx
Labels: invalid

#29 Add cookies parser and workspace retrieval
  src/features/LoginForm/LoginFormContainer.tsx
  src/features/ManagerRegistrationForm/ManagerRegistrationForm.tsx
  src/features/ManagerRegistrationForm/ManagerRegistrationFormContainer.tsx
  src/features/WorkerItem/WorkerItem.tsx
  src/features/WorkerRegistrationForm/WorkerRegistrationFormContainer.tsx
  src/features/Workspace/ItemList/ItemList.tsx
  src/features/Workspace/Workspace.tsx
  src/features/Workspace/WorkspaceContainer.tsx
  src/features/Workspace/WorkspaceWindow/WorkspaceWindow.tsx
  src/features/WorkspaceItemsForm/WorkspaceItemsForm.tsx
  src/features/WorkspaceItemsForm/WorkspaceItemsFormContainer.tsx
  src/modules/App/AppContainer.tsx
  src/modules/ManagerPage/ManagerPage.tsx
  src/services/api/Api.ts
  src/services/cookie/cookie.ts
  src/services/cookie/index.ts
  src/shared/types/models.ts
Labels: enhancement

#31 Updated the Manager page.
  src/features/WorkerScheduleForm/WorkerScheduleForm.tsx
  src/features/WorkerScheduleForm/WorkerScheduleFormContainer.tsx
  src/features/WorkspaceItemsForm/WorkspaceItemsForm.tsx
  src/features/WorkspaceItemsForm/WorkspaceItemsFormContainer.tsx
  src/modules/App/App.tsx
  src/modules/App/AppContainer.tsx
  src/modules/ManagerPage/ManagerPage.tsx
  src/services/api/Api.ts
  src/shared/types/models.ts
Labels: enhancement

#32 Add wrong timeslot notification
  src/features/Workspace/Workspace.tsx
  src/features/Workspace/WorkspaceContainer.tsx
  src/modules/App/App.tsx
  src/modules/App/AppContainer.tsx
  src/modules/WorkspacePage/WorkspacePage.tsx
  src/services/api/Api.ts
  src/shared/types/models.ts
Labels: enhancement

#33 Log out
  src/modules/App/App.tsx
  src/modules/App/AppContainer.tsx
  src/services/api/HttpActions.ts
Labels: bug

#38 Fix logout race condition. Close #37
  src/modules/App/AppContainer.tsx
Labels: bug

#36 Improve item icon placement
  src/features/WorkerItem/WorkerItem.tsx
  src/shared/workspaces/Workspaces.tsx
Labels: enhancement
